/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 03/12/2017 01:35:09          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ISO8859_1;

SET CLIENTLIB 'fbClient.dll';

CREATE DATABASE '127.0.0.1:D:\SisColegial\Db\ESCOLA.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET ISO8859_1 COLLATION ISO8859_1;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_ALUNOS_ID;
SET GENERATOR GEN_ALUNOS_ID TO 3;

CREATE GENERATOR GEN_DISCIPLINAS_ALUNOS_ID;
SET GENERATOR GEN_DISCIPLINAS_ALUNOS_ID TO 7;

CREATE GENERATOR GEN_DISCIPLINAS_ID;
SET GENERATOR GEN_DISCIPLINAS_ID TO 4;

CREATE GENERATOR GEN_DISCIPLINAS_PROFESSORES_ID;
SET GENERATOR GEN_DISCIPLINAS_PROFESSORES_ID TO 12;

CREATE GENERATOR GEN_NOTAS_ALUNOS_ID;
SET GENERATOR GEN_NOTAS_ALUNOS_ID TO 9;

CREATE GENERATOR GEN_PROFESSORES_ID;
SET GENERATOR GEN_PROFESSORES_ID TO 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE ALUNOS (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(100) NOT NULL
);

CREATE TABLE DISCIPLINAS (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(100) NOT NULL
);

CREATE TABLE DISCIPLINAS_ALUNOS (
    ID                       INTEGER NOT NULL,
    ID_ALUNO                 INTEGER NOT NULL,
    ID_DISCIPLINA_PROFESSOR  INTEGER NOT NULL
);

CREATE TABLE DISCIPLINAS_PROFESSORES (
    ID             INTEGER NOT NULL,
    ID_DISCIPLINA  INTEGER NOT NULL,
    ID_PROFESSOR   INTEGER NOT NULL
);

CREATE TABLE NOTAS_ALUNOS (
    ID                     INTEGER NOT NULL,
    ID_ALUNO_DISCIPLINA    INTEGER NOT NULL,
    NOTA_PRIMEIRO_PERIODO  DECIMAL(2,2),
    NOTA_SEGUNDO_PERIODO   DECIMAL(2,2),
    NOTA_TRABALHO          DECIMAL(2,2),
    NOTA_MEDIA             DECIMAL(2,2),
    SITUACAO               VARCHAR(50)
);

CREATE TABLE PROFESSORES (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(100) NOT NULL
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE ALUNOS ADD CONSTRAINT PK_ALUNOS PRIMARY KEY (ID);
ALTER TABLE DISCIPLINAS ADD CONSTRAINT PK_DISCIPLINAS PRIMARY KEY (ID);
ALTER TABLE DISCIPLINAS_ALUNOS ADD CONSTRAINT PK_DISCIPLINAS_ALUNOS PRIMARY KEY (ID);
ALTER TABLE DISCIPLINAS_PROFESSORES ADD CONSTRAINT PK_DISCIPLINAS_PROFESSORES PRIMARY KEY (ID);
ALTER TABLE NOTAS_ALUNOS ADD CONSTRAINT PK_NOTAS_ALUNOS PRIMARY KEY (ID);
ALTER TABLE PROFESSORES ADD CONSTRAINT PK_PROFESSORES PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE DISCIPLINAS_ALUNOS ADD CONSTRAINT FK_DISCIPLINAS_ALUNOS_ALUNOS FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS (ID);
ALTER TABLE DISCIPLINAS_ALUNOS ADD CONSTRAINT FK_DISCIPLINAS_ALUNOS_DISC_PROF FOREIGN KEY (ID_DISCIPLINA_PROFESSOR) REFERENCES DISCIPLINAS_PROFESSORES (ID);
ALTER TABLE DISCIPLINAS_PROFESSORES ADD CONSTRAINT FK_DISCIPLINAS_PROFESSORES_DISC FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINAS (ID);
ALTER TABLE DISCIPLINAS_PROFESSORES ADD CONSTRAINT FK_DISCIPLINAS_PROFESSORES_PROF FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSORES (ID);
ALTER TABLE NOTAS_ALUNOS ADD CONSTRAINT FK_NOTAS_ALUNOS_DISC_ALUNOS FOREIGN KEY (ID_ALUNO_DISCIPLINA) REFERENCES DISCIPLINAS_ALUNOS (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: ALUNOS_BI */
CREATE TRIGGER ALUNOS_BI FOR ALUNOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_alunos_id,1);
end
^

/* Trigger: DISCIPLINAS_ALUNOS_BI */
CREATE TRIGGER DISCIPLINAS_ALUNOS_BI FOR DISCIPLINAS_ALUNOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_disciplinas_alunos_id,1);
end
^

/* Trigger: DISCIPLINAS_BI */
CREATE TRIGGER DISCIPLINAS_BI FOR DISCIPLINAS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_disciplinas_id,1);
end
^

/* Trigger: DISCIPLINAS_PROFESSORES_BI */
CREATE TRIGGER DISCIPLINAS_PROFESSORES_BI FOR DISCIPLINAS_PROFESSORES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_disciplinas_professores_id,1);
end
^

/* Trigger: NOTAS_ALUNOS_BI */
CREATE TRIGGER NOTAS_ALUNOS_BI FOR NOTAS_ALUNOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_notas_alunos_id,1);
end
^

/* Trigger: PROFESSORES_BI */
CREATE TRIGGER PROFESSORES_BI FOR PROFESSORES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_professores_id,1);
end
^

SET TERM ; ^

